def buildNumber = env.BUILD_NUMBER as int
if (buildNumber > 1) milestone(buildNumber - 1)
milestone(buildNumber)

pipeline {

  agent any

  environment {
    registry = '494750395663.dkr.ecr.us-east-1.amazonaws.com/make/casper'
    app = 'wallet'
    dockerImage = '/$app'
    GIT_HASH = GIT_COMMIT.take(7)
    AWS_DEFAULT_REGION = 'us-east-1'
  }

  stages {

    stage('test') {
      when {
        anyOf {
          branch "k8s-2.1";
          branch "rc-*"
        }
      }
      steps {
        script {
          sh "echo TEST"
          // sh "sleep 36000"
        }
      }
   }

    stage('Build image') {
      when {
        anyOf {
          branch "master";
          branch "k8s-2.1";
          branch "rc-1*"
        }
      }
      steps {
        script {
          sh "until docker ps; do sleep 3; done && docker build -t $registry$dockerImage:${env.GIT_HASH} -f ci/docker/Dockerfile ."
        }
      }
   }

    stage('Push image') {
      when {
        anyOf {
          branch "master";
          branch "k8s-2.1";
          branch "rc-1*"
        }
      }
        steps {
            script {
                docker.withRegistry('https://494750395663.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:make-ecr-casper-dev') {
                    sh "docker push $registry$dockerImage:${env.VER}-${env.GIT_HASH}"
                }
            }
        }
    }

  //   stage('Clone casper-infra repo') {
  //     when {
  //       anyOf {
  //         branch "master";
  //         branch "rc-1*"
  //       }
  //     }
  //     environment {
  //       GIT_CREDS_USR = credentials('repo-git-user')
  //       GIT_CREDS_PSW = credentials('repo-git-pass')
  //     }
  //     steps {
  //       sh "git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@bitbucket.org/makellc/casper-infra.git"
  //       sh 'git config --global user.email \'jenkins@make.servies\''
  //       sh 'git config --global user.name "Jenkins CI"'
  //     }
  //   }
  }
}