name: CI Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & Check
      run: |
        npm install
        npm run ci-check
  e2e-test:
    runs-on: ubuntu-latest

    container:
      image: node:16

    strategy:
      fail-fast: false
      matrix:
#        TODO: add firefox after the test for it will be fixed
        browser: [ 'chrome' ]
        node-version: [ 16.x ]

#    services:
#      selenium:
#        image: selenium/standalone-${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: |
          npm install

      - name: Build the stack
        run: docker-compose up -d

      - name: Run E2E test on ${{ matrix.browser }}
        run: npm run test:e2e:${{ matrix.browser }}:headless
        env:
          SELENIUM_HOST: selenium
          SELENIUM_PORT: 4444
