name: CI-CD

on:
  push:
    branches: [ ci-cd-02]
  pull_request:
    branches: [ ci-cd-02 ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install

    - name: Build
      run: npm run build:chrome

    - name: Package
      run: npm run package:chrome

    - name: Upload to Chrome Web Store
      uses: mobilefirstllc/cws-publish@latest
      with:
        action: 'testers'  # one of: upload, publish, testers
        client_id: ${{ secrets.CLIENT_ID }}
        client_secret: ${{ secrets.CLIENT_SECRET }}
        refresh_token: ${{ secrets.REFRESH_TOKEN }}
        extension_id: ${{ secrets.EXTENSION_ID }}
        zip_file: './web-ext-artifacts/casper_wallet-1.2.4.zip'


    # - name: Upload & release
    #   uses: mnao305/chrome-extension-upload@v4.0.1
    #   with:
    #     file-path: './web-ext-artifacts/casper_wallet-1.2.4.zip'
    #     extension-id: ${{ secrets.EXTENSION_ID }}
    #     client-id: ${{ secrets.CLIENT_ID }}
    #     client-secret: ${{ secrets.CLIENT_SECRET }}
    #     refresh-token: ${{ secrets.REFRESH_TOKEN }}
    #     publish: false

