name: CI Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & Check
      run: |
        apt-get update -y \
        && apt-get -y install xvfb
        
        npm install
        npm run prepush-check
        xvfb-run --auto-servernum npm run ci:test:e2e:chrome 
