name: CI Check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & Check
      run: |
        curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
        echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

        apt-get -y update
        apt-get -y install google-chrome-stable
        apt-get -y install libnss3
        
        npm install
        npm run ci-check
