name: CI Check

on:
  push:
    branches: [ ci-cd]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & Check
      run: |
        npm install
        npm run build:all
        ls -la 
