name: E2E tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  onboarding-flow:
    runs-on: ubuntu-latest

    container:
      image: node:16

    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chrome', 'firefox' ]
        node-version: [ 16.x ]

    services:
      selenium:
        image: selenium/standalone-${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: |
          npm install

      - name: Run E2E test on ${{ matrix.browser }}
        run: npm run test:e2e:headless:${{ matrix.browser }}
        env:
          SELENIUM_HOST: selenium
          SELENIUM_PORT: 4444
