name: Semantic release

on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build:all
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMVER_TOKEN }}
        run: npx semantic-release